from odoo import http
from odoo.http import request
import logging
from odoo.tools import html2plaintext
_logger = logging.getLogger(__name__)
import re, json
import math


def _slugify(text):
    text = (text or "").strip().lower()
    return re.sub(r"[^a-z0-9]+", "-", text).strip("-") or "item"


def _unslugify(text):
    # Converts 'al-khobar' back to 'al khobar' so the database ilike search works
    return (text or "").replace("-", " ")


class RealEstateWebsite(http.Controller):

    def _domain_from_query(self, q):
        domain = [("state", "=", "published"), ("website_published", "=", True)]

        search = q.get("search")
        if search:
            like = f"%{search}%"
            # Search property name OR related city name
            domain += ["|", ("name", "ilike", like), ("city_id.name", "ilike", like)]

        # --- FIX: BULLETPROOF TENURE FILTER ---
        tenure_val = q.get("tenure")
        if tenure_val:
            # Checks for 'rent', 'Rent', 'sale', 'Sale' to prevent case-sensitivity bugs
            domain.append((
                "tenure",
                "in",
                [tenure_val, tenure_val.lower(), tenure_val.capitalize(), tenure_val.title()]
            ))

        # --- BULLETPROOF CITY FILTER ---
        city_val = q.get("city")
        if city_val:
            if str(city_val).isdigit():
                # Form dropdown sends an ID (e.g., "1")
                city_id = int(city_val)
                city_record = request.env['estate.city'].sudo().browse(city_id)
                if city_record.exists():
                    # Check the Many2one field OR the Char field
                    domain += ["|", ("city_id", "=", city_id), ("city", "ilike", city_record.name)]
                else:
                    domain.append(("city_id", "=", city_id))
            else:
                # SEO URL sends text (e.g., "bengaluru")
                city_name = _unslugify(city_val)
                domain += ["|", ("city_id.name", "ilike", city_name), ("city", "ilike", city_name)]

        # --- PROPERTY TYPE FILTER ---
        ptype_val = q.get("property_type")
        if ptype_val:
            if str(ptype_val).isdigit():
                # Fallback just in case an old ID is passed
                domain.append(("type_id", "=", int(ptype_val)))
            else:
                # Converts "studio-apartment" back to "studio apartment" and searches database
                ptype_name = _unslugify(ptype_val)
                domain.append(("type_id.name", "ilike", ptype_name))

        # Handle numeric ranges
        def _range(key, field):
            min_v = q.get(f"{key}_min")
            max_v = q.get(f"{key}_max")
            if min_v: domain.append((field, ">=", float(min_v)))
            if max_v: domain.append((field, "<=", float(max_v)))

        _range("price", "price")
        _range("rent", "rent_price")
        _range("bedrooms", "bedrooms")
        _range("bathrooms", "bathrooms")

        if q.get("state_id"): domain.append(("state_id", "=", int(q.get("state_id"))))
        if q.get("country_id"): domain.append(("country_id", "=", int(q.get("country_id"))))

        return domain

    # FIX: Use generic path variables so we can decipher if the user typed a city OR a tenure
    @http.route([
        '/properties',
        '/properties/page/<int:page>',
        '/properties/<string:tenure>',
        '/properties/<string:tenure>/page/<int:page>',
        '/properties/<string:tenure>/<string:city_name>',
        '/properties/<string:tenure>/<string:city_name>/page/<int:page>',
        # --- NEW ROUTES FOR PROPERTY TYPE ---
        '/properties/<string:tenure>/<string:city_name>/<string:property_type>',
        '/properties/<string:tenure>/<string:city_name>/<string:property_type>/page/<int:page>',
    ], type='http', auth='public', website=True, sitemap=True)
    def properties(self, tenure=None, city_name=None, property_type=None, page=1, **kwargs):
        # 1. Capture filters from URL path or fallback to query string
        tenure = tenure or kwargs.get('tenure')
        city_name = city_name or kwargs.get('city')
        property_type = property_type or kwargs.get('property_type')

        # Ignore the 'any' placeholders generated by JS
        if tenure == 'any': tenure = None
        if city_name == 'any': city_name = None
        if property_type == 'any': property_type = None

        # 2. Clean kwargs and update them so _domain_from_query works seamlessly
        kwargs.pop('tenure', None)
        kwargs.pop('city', None)
        kwargs.pop('property_type', None)

        if tenure: kwargs['tenure'] = tenure
        if city_name: kwargs['city'] = city_name
        if property_type: kwargs['property_type'] = property_type

        page = int(page)
        pp = 12

        # 3. Get domain and properties
        domain = self._domain_from_query(kwargs)
        Prop = request.env['estate.property'].sudo()
        count = Prop.search_count(domain)

        # 4. Build dynamic pager URL preserving the SEO hierarchy
        pager_base_url = '/properties'
        if tenure or city_name or property_type:
            pager_base_url += f"/{tenure or 'any'}"
            if city_name or property_type:
                pager_base_url += f"/{city_name or 'any'}"
                if property_type:
                    pager_base_url += f"/{property_type}"

        pager = request.website.pager(
            url=pager_base_url,
            total=count,
            page=page,
            step=pp,
            scope=5,
            url_args={k: v for k, v in kwargs.items() if k not in ('tenure', 'city', 'property_type')}
        )

        props = Prop.search(domain, limit=pp, offset=pager['offset'], order="priority desc, id desc")

        # 5. Data for filters
        cities = request.env['estate.city'].sudo().search([])
        property_types = request.env['estate.property.type'].sudo().search([])

        return request.render('realestate_website.properties', {
            'properties': props,
            'pager': pager,
            'q': kwargs,
            'cities': cities,
            'property_types': property_types,
            'active_tenure': tenure,
            'active_city_slug': city_name,
            'active_type_slug': property_type,
        })

    # --- UPDATED ROUTE FOR DEEP SEO ---
    @http.route([
        # Keep old short routes as fallbacks so existing links don't break (404 Error)
        '/property/<string:slug>-<int:prop_id>',
        '/property/<int:prop_id>',

        # --- NEW DEEP SEO ROUTES ---
        '/property/<string:tenure>/<string:property_type>/<string:city>/<string:slug>-<int:prop_id>',
        '/property/<string:tenure>/<string:property_type>/<string:city>/<int:prop_id>'
    ], type='http', auth='public', website=True, sitemap=True)
    def property(self, prop_id, slug=None, tenure=None, property_type=None, city=None, **kw):
        prop = request.env['estate.property'].sudo().browse(prop_id).exists()

        # 1. Check if property exists
        if not prop:
            return request.not_found()

        # 2. Check publication status safely
        is_pub = getattr(prop, 'website_published', getattr(prop, 'is_published', False))
        if not is_pub and prop.state != 'published':
            # Allow website editors/admins to see unpublished properties!
            if not request.env.user.has_group('website.group_website_restricted_editor'):
                return request.not_found()

        # 3. Clean the Description for SEO (Removes HTML tags and limits length)
        seo_desc = getattr(prop, 'website_meta_description', False)
        if not seo_desc and getattr(prop, 'description', False):
            # html2plaintext safely converts rich-text HTML into raw text
            seo_desc = html2plaintext(prop.description).replace('\n', ' ').replace('\r', '').strip()
            seo_desc = seo_desc[:157] + '...' if len(seo_desc) > 160 else seo_desc

        # 4. Grab absolute image URL for OpenGraph & Twitter
        og_image = False
        if getattr(prop, 'image_1920', False):
            # Use request.httprequest.url_root to ensure absolute URLs
            og_image = f"{request.httprequest.url_root.rstrip('/')}/web/image/estate.property/{prop.id}/image_1920"

        # 5. Schema.org JSON-LD (Rich Snippets)
        json_ld = {
            "@context": "https://schema.org",
            "@type": "SingleFamilyResidence",
            "name": prop.name,
            "description": seo_desc or prop.name,
            "url": request.httprequest.url,
        }
        if og_image:
            json_ld["image"] = og_image

        # 6. Build the perfect QContext for Odoo's core website.layout
        qcontext = {
            'property': prop,

            # --- ODOO NATIVE SEO HOOKS ---
            # Required by Odoo base template for Edit/Publish buttons and fallbacks
            'main_object': prop,

            # Odoo automatically prepends this to " | Your Website Name"
            'additional_title': getattr(prop, 'website_meta_title', False) or prop.name,

            # Odoo layout natively catches this to render <meta name="description">
            'website_meta_description': seo_desc,

            # Odoo layout natively catches this for <meta name="keywords">
            'website_meta_keywords': getattr(prop, 'website_meta_keywords', ''),

            # --- CUSTOM FALLBACK VARS ---
            'canonical_url': request.httprequest.url,
            'og_image': og_image,
            'json_ld_str': json.dumps(json_ld, ensure_ascii=False),
        }

        # Odoo's layout explicitly tries to run seo_object.sudo().get_website_meta()
        # We only pass `seo_object` if your model inherently inherits the Odoo SEO Mixin,
        # otherwise Odoo will crash trying to call a function that doesn't exist.
        if hasattr(prop, 'get_website_meta'):
            qcontext['seo_object'] = prop

        return request.render('realestate_website.property', qcontext)

    @http.route(['/property/inquiry'], type='http', auth='public', website=True, methods=['POST'])
    def property_inquiry(self, **post):
        # Validate property
        try:
            prop_id = int(post.get('property_id') or 0)
        except Exception:
            prop_id = 0
        Prop = request.env['estate.property'].sudo()
        prop = Prop.browse(prop_id).exists()
        if not prop:
            return request.redirect('/properties')

        Lead = request.env['crm.lead'].sudo()
        vals = {
            'name': f"Website Inquiry: {prop.name}",
            'property_id': prop.id,  # your custom field on crm.lead
            'contact_name': post.get('name') or '',
            'email_from': post.get('email') or '',
            'phone': post.get('phone') or '',
            'description': post.get('message') or '',
        }

        # If Odoo has the 'type' field (Leads feature enabled), create as opportunity
        if 'type' in Lead.fields_get():
            vals['type'] = 'opportunity'

        # Optional: assign sales user/team
        if prop.sales_user_id:
            vals['user_id'] = prop.sales_user_id.id
        team = request.env.ref('crm.crm_team_1', raise_if_not_found=False)
        if team:
            vals['team_id'] = team.id

        try:
            lead = Lead.create(vals)
            _logger.info("Website inquiry created lead id=%s for property id=%s", lead.id, prop.id)
        except Exception:
            _logger.exception("Website inquiry: failed to create lead for property %s", prop.id)
            return request.redirect(f"{prop._get_website_url()}?error=1")

        return request.redirect(f"{prop._get_website_url()}?thanks=1")